module.exports = {
    /*mySidebar: [
      {
        type: 'autogenerated',
        dirName: '.', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
      },
    ],*/
    someSidebar: {
        Docusaurus: ['test/doc1', 'doc2', 'doc3'],
        Landing: ['whatispp', 'howtostart', 'credits'],
        "UES - Unity Event System": [
            'events',
            'Events/edesign',
            'Events/etypesandcond',
            {
                type: 'category',
                label: 'Block types',
                items: [{
                    type: 'autogenerated',
                    dirName: 'blocktypes'

                }],
            },
            'conditions'
        ],
        Design: ['designInfo'],
		"Input Handling": [{
			type: 'doc',
			id: 'Inputs/inputManager',
			label: 'Input Manager',
		}],
        Features: ['mdx'],
    },
};