module.exports = {
    /*mySidebar: [
      {
        type: 'autogenerated',
        dirName: '.', // generate sidebar slice from the docs folder (or versioned_docs/<version>)
      },
    ],*/
    someSidebar: {
        Docusaurus: ['test/doc1', 'doc2', 'doc3'],
        Landing: ['whatispp', 'howtostart'],
        "UES - Unity Event System": ['events', {
            type: 'category',
            label: 'Block types',
            items: [{
                type: 'autogenerated',
                dirName: 'blocktypes'

            }],
        }, 'conditions'],
        Design: ['designInfo'],
        Features: ['mdx'],
    },
};